---
- hosts: d
  tasks:
    - name: Install a list of packages
      apt:
        update_cache: yes
        name: "{{ packages }}"
      vars:
        packages:
        - htop
        - atop
        - net-tools
        - mc