---
- hosts: k8s-masters
  become: yes
  become_method: su
  tasks:
    - name: Install a list of packages
      apt:
        name: [atop, htop, zabbix-agent, open-vm-tools, curl, gnupg2, apt-transport-https, ca-certificates, software-properties-common]
        state: present
        update_cache: true

    - name: copy apt
      copy: src=Kubernetes/k8s.list dest=/etc/apt/sources.list.d/

    - name: copy root config
      copy: src=files/.bashrc dest=/root/

    - name: run master nodes
      shell: |
        cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
        curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
        apt update
        apt install -y docker-ce docker-ce-cli containerd.io
        systemctl enable docker
        apt install -y kubeadm kubectl kubelet=1.15.4-00
        echo "\n10.55.0.141 k8s-master-1\n10.55.0.142 k8s-master-2\n10.55.0.143 k8s-master-3\n10.55.0.144 k8s-worker-1\n10.55.0.145 k8s-worker-2\n10.55.0.146 k8s-worker-3\n" >> /etc/hosts
        sysctl net.bridge.bridge-nf-call-iptables=1
        echo "net.bridge.bridge-nf-call-iptables=1\n" >> /etc/sysctl.conf
        sysctl -p
#        systemctl enable keepalived
#        service keepalived restart
#        echo "net.ipv4.ip_forward = 1\nnet.ipv4.ip_nonlocal_bind = 1\nnet.ipv4.conf.ens192.arp_announce = 2\nnet.ipv4.conf.ens192.arp_ignore = 1" >> /etc/sysctl.conf
#        sysctl -p
