---
- hosts: k8s-masters
  become: yes
  become_method: su
  tasks:
    - name: Install a list of packages
      apt:
        name: [keepalived]
        state: present
        update_cache: true

    - name: Push config file
      copy: src=files/keepalived.conf dest=/etc/keepalived/

    - name: system config
      shell: |
        echo "\nnet.ipv4.ip_forward = 1\nnet.ipv4.ip_nonlocal_bind = 1\nnet.ipv4.conf.ens192.arp_announce = 2\nnet.ipv4.conf.ens192.arp_ignore = 1\n" >> /etc/sysctl.conf
        sysctl -p
        systemctl enable keepalived
        service keepalived restart
