#!/bin/bash
#
# /etc/init.d/elk -- startup script for elk
#
### BEGIN INIT INFO
# Provides:          elk
# Required-Start:    $network $remote_fs $named
# Required-Stop:     $network $remote_fs $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts elasticsearch
# Description:       Starts elasticsearch using start-stop-daemon
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script ELK "
    service elasticsearch start
    sleep 30
    service logstash start
    sleep 30
    service kibana start
    ;;
  stop)
    echo "Stopping script ELK"
    service elasticsearch stop
    service logstash stop
    service kibana stop
    ;;
  *)
    echo "Usage: /etc/init.d/elk {start|stop}"
    exit 1
    ;;
esac

exit 0
