concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "k8s-docker-docker"
  url = "https://k8s-gitlab/"
  token = "UbBkfqGTnP1c2zkDxsiM"
  tls-ca-file = "/etc/gitlab-runner/k8s-gitlab.crt"
  executor = "docker"
  environment = ["GIT_SSL_NO_VERIFY=true"]
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "alpine"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]

[[runners]]
  name = "k8s-docker-shell"
  url = "https://k8s-gitlab/"
  token = "tWcseqcJHbakGpxXJgqo"
  tls-ca-file = "/etc/gitlab-runner/k8s-gitlab.crt"
  executor = "shell"
  shell = "bash"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
