apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tmp
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: local-storage
#  mountOptions:
#    - hard
#    - nfsvers=4.1
  nfs:
    path: /_tmp
    server: 1.1.1.15
